### ISSUE TITLE
Krita shows multiple times in "open with" dialog (mint/mate 18 x64)

### ISSUE THREAD

**Issue by unxed** [mate-desktop/mate-menus#46]
https://bugs.kde.org/show_bug.cgi?id=375329

They say it's probably DE bug. Not sure where to submit this issue. Point me to the correct project if needed, please.

**Comment by raveit65** [comment]
At linuxmint as told in other report.

**Comment by epgfm** [comment]
@raveit65, I've reproduced on Ubuntu MATE Zetsy, so I think upstream might be the place. :x 
![image](https://cloud.githubusercontent.com/assets/10635269/24298874/a2cbc7f6-10a7-11e7-815d-64e301e204a7.png)

**Comment by raveit65** [comment]
This shows only that mint and ubuntu use the same package repo ;-)
Please read comment from mentioned kde report.
I will try to  reproduce it on a rpm system.

**Comment by unxed** [comment]
https://bugs.launchpad.net/linuxmint/+bug/1675816

**Comment by raveit65** [comment]
Ok, i have the same issue here, btw. it isn't a bug from our side ;-).
We do the right thing.
```
[root@f25-origin /]# ls -l /usr/share/applications/
insgesamt 1200
**cut here**
drwxr-xr-x. 2 root root  4096  8. Jul 2016  kde
drwxr-xr-x. 2 root root  4096  8. Jul 2016  kde4
-rw-r--r--. 1 root root  8569 30. Jan 2016  kde-mimeapps.list
-rwxr-xr-x. 1 root root  1199 14. Dez 19:16 krita_bmp.desktop
-rwxr-xr-x. 1 root root  1268 14. Dez 19:16 krita_brush.desktop
-rwxr-xr-x. 1 root root  1198 14. Dez 19:16 krita_csv.desktop
-rwxr-xr-x. 1 root root  4891 14. Dez 19:16 krita_exr.desktop
-rwxr-xr-x. 1 root root  1271 14. Dez 19:16 krita_heightmap.desktop
-rwxr-xr-x. 1 root root  1257 14. Dez 19:16 krita_jpeg.desktop
-rwxr-xr-x. 1 root root  1233 14. Dez 19:16 krita_odg.desktop
-rwxr-xr-x. 1 root root  1272 14. Dez 19:16 krita_ora.desktop
-rwxr-xr-x. 1 root root  1262 14. Dez 19:16 krita_pdf.desktop
-rwxr-xr-x. 1 root root  1199 14. Dez 19:16 krita_png.desktop
-rwxr-xr-x. 1 root root  1332 14. Dez 19:16 krita_ppm.desktop
-rwxr-xr-x. 1 root root  1346 14. Dez 19:16 krita_psd.desktop
-rwxr-xr-x. 1 root root  1505 14. Dez 19:16 krita_raw.desktop
-rwxr-xr-x. 1 root root  1201 14. Dez 19:16 krita_tga.desktop
-rwxr-xr-x. 1 root root  1257 14. Dez 19:16 krita_tiff.desktop
-rwxr-xr-x. 1 root root  1258 14. Dez 19:16 krita_xcf.desktop
-rwxr-xr-x. 1 root root  1458  4. Mär 17:15 ktelnetservice5.desktop
-rw-r--r--. 1 root root 17430 18. Feb 22:07 libreoffice-calc.desktop
**cut here**
```
any open questions?

**Comment by raveit65** [comment]
In other words, if distro maintainer decided to install 16 desktop files, we will see 16  versions of the same application in our property dialog ;-)

**Comment by epgfm** [comment]
Thanks @raveit65, so this is distro-specific, and the bug should be reported against Ubuntu MATE, Mint and Fedora and not against Krita?

**Comment by raveit65** [comment]
Not sure, the question is if the several desktop files are in upstream tarball or added by a distro maintainer.
In both cases you will get a horrible discussion about why this is needed.

**Comment by unxed** [comment]
Not sure if it matters, but I have the same issue with some wine applications like FastStone Image Viewer.

**Comment by boudewijnrempt** [comment]
No. I'm the Krita maintainer and I can tell you you're not doing the right thing. This is the third or fourth time I'm encountering this issue with desktops: it comes from a lack of familiarity with the freedesktop .desktop file standard. Those extra .desktop files come with the plugins that enable Krita to load extra file formats. They have a "NoDisplay=true" line which means that you shouldn't display them in your gui.

See: https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html which says "NoDisplay means "this application exists, but don't display it in the menus". This can be useful to e.g. associate this application with MIME types, so that it gets launched from a file manager (or other apps), without having a menu entry for it (there are tons of good reasons for this, including e.g. the netscape -remote, or kfmclient openURL kind of stuff). ".

**Comment by flexiondotorg** [comment]
@boudewijnrempt I confirm that Nautilus only shows one entry for Krita in the _Open With_ context menu and also only shows one Krita entry in the _Open With -> Other Application..._ So Nautilus is not displaying the Krita plugins and Caja is doing the wrong thing.

However, what is the point of all these .desktop files exactly? If they are not displayed in Nautilus (and Caja) they can't be invoked unless I choose _Open With -> Other Application... -> View All Applications_ from which I now see 16 indistinguishable Krita entries. How do you anticipate these .desktop entries are exposed to the user?

**Comment by unxed** [comment]
> I now see 16 indistinguishable Krita entries

Confirming. IMHO it can be considered a bug also.

**Comment by flexiondotorg** [comment]
If you're suggesting that it is a bug in View All Applications (something Nautilus and Nemo do) and the 16 Krita plugin entries should not displayed there also, I'm really at a loss as to their purpose.

**Comment by boudewijnrempt** [comment]
I'm sorry, but I'm getting a bit impatient here. 

What the purpose is? 

Krita makes it possible for plugins to extend Krita with additional file format support. Those plugins come with a desktop file that tell the desktop that krita can load those file types. Of course Krita's main desktop file cannot have the full list of supported file types, because that's implemented by plugins. Most of those plugins are shipped with Krita, but that is not necessary. People can create extra import/export plugins that still need desktop files so your desktop can know that Krita can load this file format.

This, by the way, has been the case since 2004 or so; it's not new, it's not weird. Being at a loss as to their purpose means you don't understand the .desktop file specification.

Just implement support for the nodisplay tag already.

**Comment by flexiondotorg** [comment]
I do understand the .desktop specification and it is supported. However `NoDisplay=true` is not honoured in Caja's context menu, which I explained earlier, and the Krita plugins are not exposed in the menus therefore there is no bug in `mate-menus`.

**Comment by monsta** [comment]
I'll just leave this here: https://github.com/mate-desktop/caja/issues/697

**Comment by kn00tcn** [comment]
lolwut, the file format suffix of each .desktop in that ls list makes the purpose obvious

shouldnt the entry for the specific format show only when right clicking that format? why would right clicking a png file display the _bmp application entry? this is the issue
