### ISSUE TITLE
wrong horizontal position in dual monitor configuration

### ISSUE THREAD

**Issue by wladk** [mate-desktop/mate-menus#50]
#### Expected behaviour
the horizontal position must be calculated on each monitor separately, so it must be aligned to left of button

#### Actual behaviour
the horizontal position calculates on total width of both monitors and it is aligned to right of button

#### Steps to reproduce the behaviour
Then using dual monitor, and set a menu into left corner of right monitor, it poping up between two montiors

to temporary fix this, I made a changes  to /usr/lib/mate-menu/mate-menu.py:
string 815
         else:
                # Align to the right of the entry
-newX = entryX - ourWidth
+newX = entryX

#### MATE general version
1.16

#### Package version
mate-menu.noarch  17.10.1-1.fc25 

#### Linux Distribution
Fedora 25 x86_64

**Comment by flexiondotorg** [comment]
I think this issue is for `mate-menu` which is maintained by me in BitBucket - https://bitbucket.org/ubuntu-mate/mate-menu

It looks like this issue might be what you're describing? 

  * https://bitbucket.org/ubuntu-mate/mate-menu/issues/21/mate-menu-is-suddenly-right-aligned-to-its

I'll close this issue, please comment on the repo I've mentioned above and submit a pull request. Thanks ☺️
