### ISSUE TITLE
I can not more  edit menus 

### ISSUE THREAD

**Issue by elvecio** [mate-desktop/mate-menus#51]
I can not more  edit menus with the right-click mouse (using debian strectch). I do not know if this is a normal behavior now, in any case, if normal,  you need to change the help pages where you specifically suggest using the right mouse button to edit the panel menus.

**Comment by o-alquimista** [comment]
I'm not sure what is elvecio trying to say, but it might be the same thing as I experienced.

**How to reproduce:**
Right-click menus, choose "edit menus"

**What happens:**
Nothing. No loading animation, no response. Nothing opens.

**Expected behavior:**
Mozo "menu editor" would open.

![captura de tela em 2017-09-02 16-09-07](https://user-images.githubusercontent.com/25424263/29998118-268d60f6-8ff9-11e7-9b8d-fb1ed141b80e.png)

**Comment by flexiondotorg** [comment]
This issue is fixed in MATE itself and also fixed in Ubuntu MATE 17.10.
