### ISSUE TITLE
Can't see the menu while an "always on top" window cover it

### ISSUE THREAD

**Issue by andreabravetti** [mate-desktop/mate-menus#62]
#### Expected behaviour

The menu should be always visible, a new always on top window created on top of averything.

#### Actual behaviour

Can't see the menu while an "always on top" window cover it

#### Steps to reproduce the behaviour

Set a windows as always on top and place it where the menu should appear, or simply maximize it, then try to open the menu

#### MATE general version

1.20

#### Linux Distribution

Mint 19 (Mate Edition)

**Comment by lukefromdc** [comment]
This might be a bug in marco (the window manager) rather than mate-menus

**Comment by lukefromdc** [comment]
I just confirmed that with my branch of compiz-reloaded(https://gitlab.com/lukefromdc/compiz/tree/dev-focus_WIP) and mate menus/panel/etc 1.21 and Firefox in "always on top" the main menu is in fact visible over the "always on top" window. Have a complex session running now that will collapse onto one desktop if I switch it to marco, but this is enough to confirm the issue is with marco. Since any other window manager does not have this problem, its a window management issue and thus an issue in marco.

Since issues can't be moved to another package, please open this as a new issue against marco and close this one.

**Comment by andreabravetti** [comment]
closing this issue and opening a new one against marco
